# Generated by Django 4.0 on 2021-12-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_product_tb_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usercourier'),
        ),
    ]
