# Generated by Django 4.0 on 2021-12-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tables_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourier',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='tables_tb',
        ),
    ]
