# Generated by Django 4.0 on 2021-12-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usercourier_status_delete_tables_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
